//! The interview problem bank.
//!
//! Split out because it is data, not logic: nearly two thousand lines of
//! static entries that were burying the runtime behavior they sit next to.
//! Candidate-visible copies of these live in `web/problems/<page>.json`, named
//! for each problem's scenario and generated by `scripts/gen-problems.py`
//! (`web/problem-pages.json` maps an id to its page and title); the rubric
//! fields here
//! stay server-side. What the candidate is actually asked, and the
//! interviewer's
//! clarifications, follow-ups and hints for it, are in `problem_variants.rs`,
//! generated from `problem-bank/variants.json`.

use super::{Problem, ProblemVariant};

/// One row of a generated `(id, value)` table.
fn lookup<T>(table: &'static [(&'static str, T)], problem_id: &str) -> Option<&'static T> {
    table
        .iter()
        .find_map(|(id, value)| (*id == problem_id).then_some(value))
}

pub fn topics_for(problem_id: &str) -> Option<&'static [&'static str]> {
    lookup(super::problem_topics::PROBLEM_TOPICS, problem_id).copied()
}

pub fn variant_for(problem_id: &str) -> Option<&'static ProblemVariant> {
    lookup(super::problem_variants::PROBLEM_VARIANTS, problem_id)
}

/// The reviewer's solution notes, for the report prompt only. A live
/// interviewer holding a written walkthrough paraphrases it, and a hint becomes
/// the answer.
pub(super) fn guide_for(problem_id: &str) -> Option<&'static str> {
    lookup(super::problem_guides::PROBLEM_GUIDES, problem_id).copied()
}

pub const DEFAULT_PROBLEM_ID: &str = "two-sum";

pub use super::problem_rubrics::PROBLEM_RUBRICS as PROBLEMS;

/// By id or by page name. The browser sends the page name; an id still arrives
/// from a room minted before pages had names, and from the server's own tests.
///
/// Two single passes rather than one pass asking each problem for its variant:
/// `variant()` is itself a scan, and nested it made a lookup thousands of
/// comparisons, run twice for every row of an account's history.
pub fn find_problem(id: &str) -> Option<&'static Problem> {
    let published = super::problem_variants::PROBLEM_VARIANTS
        .iter()
        .find_map(|(published, variant)| (variant.page == id).then_some(*published))
        .unwrap_or(id);
    PROBLEMS.iter().find(|problem| problem.id == published)
}

/// [`find_problem`], or the default for a name the bank does not have: a bad
/// link opens an interview rather than an error page.
pub fn get_problem(problem_id: Option<&str>) -> &'static Problem {
    problem_id
        .and_then(find_problem)
        .unwrap_or_else(|| find_problem(DEFAULT_PROBLEM_ID).expect("default problem exists"))
}
