"""What the generator writes: the browser pages, judges, map and Rust tables."""

from __future__ import annotations

import json
from pathlib import Path

from .bank import (
    DEFAULT_PROBLEM_ID,
    DIRS,
    JUDGE_OUTPUT_DIR,
    JUDGE_SOURCE,
    OUTPUT_DIR,
    PAGE_MAP_OUTPUT,
    ROOT,
    RUST_GUIDES,
    RUST_RUBRICS,
    RUST_TOPICS,
    RUST_VARIANTS,
    VARIANT_SOURCE,
    public_metadata,
    read_json,
    validated_problems,
)
from .rules import page_slug, validated_guides, validated_variants


def candidate_problem(entry: dict) -> dict:
    """Everything the interview page is given, and nothing it is not.

    Built up rather than filtered down from the bank entry, so a field added to
    the bank later stays on the server until someone decides the candidate
    should see it.

    The published title rides along as `source`, shown small beside the
    scenario so a candidate can find the problem again afterwards. The scenario
    is still what the page poses: no number, no statement, no published examples.
    """
    posed_problem, variant = entry["problem"], entry["variant"]
    return {
        "page": page_slug(variant["title"]),
        "title": variant["title"],
        **(
            {"source": posed_problem["title"]}
            if posed_problem.get("origin", "leetcode") == "leetcode"
            else {}
        ),
        "difficulty": posed_problem["difficulty"],
        "brief": variant["brief"],
        "examples": entry["examples"],
        "starterCode": posed_problem["starterCode"],
        "interviewMetadata": public_metadata(posed_problem),
    }


def rust_str(text: str) -> str:
    """A Rust string literal. JSON escapes are not all Rust escapes.

    Every character outside printable ASCII is escaped, control characters
    included: a carriage return or a tab written literally is still a string,
    but other controls can stop the generated table compiling.
    """
    escaped = "".join(
        {"\\": "\\\\", '"': '\\"', "\n": "\\n"}.get(character, character)
        if character.isascii() and (character.isprintable() or character == "\n")
        else f"\\u{{{ord(character):x}}}"
        for character in text
    )
    return f'"{escaped}"'


def rust_strs(items: list[str]) -> str:
    return "&[" + ", ".join(rust_str(item) for item in items) + "]"


def rust_variants(problems: list[dict], variants: dict) -> str:
    rows = []
    for problem in problems:
        entry = variants[problem["id"]]
        variant = entry["variant"]
        clarifications = ", ".join(
            f"({rust_str(item['question'])}, {rust_str(item['answer'])})"
            for item in variant["clarifications"]
        )
        starters = ", ".join(
            f"({rust_str(language)}, {rust_str(code)})"
            for language, code in entry["problem"]["starterCode"].items()
        )
        rows.append(
            "\n".join(
                [
                    f"    ({rust_str(problem['id'])}, ProblemVariant {{",
                    f"        title: {rust_str(variant['title'])},",
                    f"        page: {rust_str(page_slug(variant['title']))},",
                    f"        brief: {rust_strs(variant['brief'])},",
                    f"        contract: {rust_str(variant['contract'])},",
                    f"        constraints: {rust_strs(entry['problem']['constraints'])},",
                    f"        clarifications: &[{clarifications}],",
                    f"        follow_ups: {rust_strs(variant['followUps'])},",
                    f"        hints: {rust_strs(variant['hints'])},",
                    f"        starters: &[{starters}],",
                    "    }),",
                ]
            )
        )
    return (
        "//! Generated by scripts/gen-problems.py; do not edit by hand.\n\n"
        "use super::ProblemVariant;\n\n"
        "#[rustfmt::skip]\n"
        "pub const PROBLEM_VARIANTS: &[(&str, ProblemVariant)] = &[\n"
        + "\n".join(rows)
        + "\n];\n"
    )


def rust_guides(guides: dict) -> str:
    rows = [
        f"    ({rust_str(problem_id)}, {rust_str(text)}),"
        for problem_id, text in guides.items()
    ]
    return (
        "//! Generated by scripts/gen-problems.py; do not edit by hand.\n"
        "//!\n"
        "//! Solution notes for the report reviewer. The source and the MIT license\n"
        "//! they are used under are in problem-bank/guides.json.\n\n"
        "#[rustfmt::skip]\n"
        "pub const PROBLEM_GUIDES: &[(&str, &str)] = &[\n" + "\n".join(rows) + "\n];\n"
    )


def rust_topics(problems: list[dict]) -> str:
    rows = [
        f"    ({rust_str(problem['id'])}, {rust_strs(problem['topics'])}),"
        for problem in problems
    ]
    return (
        """//! Generated by scripts/gen-problems.py; do not edit by hand.\n\n\
#[rustfmt::skip]\n\
pub const PROBLEM_TOPICS: &[(&str, &[&str])] = &[\n"""
        + "\n".join(rows)
        + "\n];\n"
    )


def rust_rubrics(problems: list[dict], variants: dict) -> str:
    rows = []
    for problem in problems:
        title = (
            variants[problem["id"]]["variant"]["title"]
            if problem.get("origin") == "original"
            else problem["title"]
        )
        rows.append(
            "\n".join(
                [
                    "    Problem {",
                    f"        id: {rust_str(problem['id'])},",
                    f"        title: {rust_str(title)},",
                    f"        difficulty: {rust_str(problem['difficulty'])},",
                    f"        summary: {rust_str(problem['summary'])},",
                    f"        optimal: {rust_str(problem['optimal'])},",
                    f"        pitfalls: {rust_str(problem['pitfalls'])},",
                    "    },",
                ]
            )
        )
    return (
        "//! Generated by scripts/gen-problems.py; do not edit by hand.\n\nuse super::Problem;\n\n#[rustfmt::skip]\npub const PROBLEM_RUBRICS: &[Problem] = &[\n"
        + "\n".join(rows)
        + "\n];\n"
    )


def generated() -> dict[Path, str]:
    """Every file this script owns, as path -> exact contents."""
    files: dict[Path, str] = {}
    problems = validated_problems()
    variants = validated_variants(
        problems, read_json(JUDGE_SOURCE), read_json(VARIANT_SOURCE)
    )
    # Every consumer that has an id and wants the page or the title reads this
    # map, rather than rebuilding it from the pages or re-deriving the slug.
    # Only the paths that start from a published id or name fetch it: an old
    # link, history saved before pages had names, and the lobby's opt-in toggle.
    # A scenario link loads a page and a judge that carry no published id; the
    # page names its published title once, in the `source` it shows small.
    pages = {}
    for problem in problems:
        entry = variants[problem["id"]]
        page = candidate_problem(entry)
        pages[problem["id"]] = {
            "page": page["page"],
            "title": page["title"],
            **({"source": page["source"]} if "source" in page else {}),
            **({"default": True} if problem["id"] == DEFAULT_PROBLEM_ID else {}),
        }
        files[OUTPUT_DIR / f"{page['page']}.json"] = json.dumps(page, indent=2) + "\n"
        files[JUDGE_OUTPUT_DIR / f"{page['page']}.json"] = (
            json.dumps(entry["judge"], indent=2) + "\n"
        )
    files[PAGE_MAP_OUTPUT] = json.dumps(pages, indent=2) + "\n"
    files[RUST_TOPICS] = rust_topics(problems)
    files[RUST_VARIANTS] = rust_variants(problems, variants)
    files[RUST_GUIDES] = rust_guides(validated_guides(problems))
    files[RUST_RUBRICS] = rust_rubrics(problems, variants)
    return files


def orphans(files: dict[Path, str]) -> list[Path]:
    """Generated files this run would not write.

    A problem removed from the bank leaves its statement and its judge on disk
    otherwise, and for the judge that means an answer key still being served for
    a problem nobody can be given any more.
    """
    on_disk = (path for directory in DIRS for path in sorted(directory.glob("*.json")))
    return [path for path in on_disk if path not in files]


def drifted(files: dict[Path, str]) -> list[str]:
    """What `--check` reports, as repo-relative paths, in either direction."""
    changed = [
        str(path.relative_to(ROOT))
        for path, text in files.items()
        if not path.exists() or path.read_text() != text
    ]
    removed = [
        f"{path.relative_to(ROOT)} (no longer in the bank)" for path in orphans(files)
    ]
    return sorted(changed + removed)
