#!/usr/bin/env python3
"""Regenerate lobby problem cards from problem-bank/problems.json."""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
import textwrap
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "problem-bank" / "problems.json"
INDEX = ROOT / "web" / "index.html"
# Matched without their indentation, which the surrounding markup owns and has
# already changed once: wrapping the grid in a `<details>` moved it two columns
# right, and the six-space literals these used to be went on matching only
# because `str.find` searches for a substring. The block round-tripped, so
# `--check` stayed green while the anchors were wrong. Whatever indentation the
# page uses is read off the opening tag and written back, so nesting the section
# again is not a silent break.
START = '<section class="problem-grid" aria-label="Problems">'
END = "</section>"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def read_json(path: Path) -> object:
    return json.loads(path.read_text())


def card(problem: dict[str, object]) -> str:
    topics = ", ".join(html.escape(topic) for topic in problem["topics"])
    meta = f"{html.escape(problem['difficulty'])} &middot; {topics}"
    return "\n".join(
        [
            f'  <button class="problem-card" type="button" data-problem="{html.escape(problem["id"])}" data-difficulty="{html.escape(problem["difficulty"])}">',
            f'    <span class="problem-title">{html.escape(problem["title"])}</span>',
            f'    <span class="problem-meta">{meta}</span>',
            "  </button>",
        ]
    )


def generated(problems: list) -> str:
    cards = "\n".join(card(problem) for problem in problems)
    return "\n".join(
        [
            START,
            "  <!-- Generated by scripts/gen-problem-cards.py from problem-bank/problems.json. Do not edit by hand. -->",
            cards,
            END,
        ]
    )


def main() -> int:
    args = parse_args()
    html_text = INDEX.read_text()
    opening = re.search(
        rf"^([ \t]*){re.escape(START)}[ \t]*$", html_text, flags=re.MULTILINE
    )
    if opening is None:
        print(f"{INDEX}: could not find the problem-grid opening tag", file=sys.stderr)
        return 1

    indent = opening.group(1)
    # The close has to sit at the same indentation, so a nested `</section>`
    # cannot end the block early.
    end = re.compile(rf"^{indent}{re.escape(END)}[ \t]*$", flags=re.MULTILINE).search(
        html_text, opening.end()
    )
    if end is None:
        print(
            f"{INDEX}: the problem-grid section is not closed at its own indentation",
            file=sys.stderr,
        )
        return 1

    problems = read_json(SOURCE)
    block = textwrap.indent(generated(problems), indent)
    updated = html_text[: opening.start()] + block + html_text[end.end() :]
    if args.check:
        if updated != html_text:
            print(
                "web/index.html problem cards are stale; run: python3 scripts/gen-problem-cards.py",
                file=sys.stderr,
            )
            return 1
        return 0

    if updated != html_text:
        INDEX.write_text(updated)
        print(f"updated {len(problems)} problem cards in web/index.html")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
