#!/usr/bin/env python3
"""Regenerate lobby problem cards from problem-bank/problems.json and web/problem-pages.json."""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
import textwrap
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "problem-bank" / "problems.json"
# The scenario page and title for each id, from the map gen-problems.py writes
# rather than from variants.json, so the one script that validates variants is
# the only one that reads them. Run it first.
PAGE_MAP = ROOT / "web" / "problem-pages.json"
INDEX = ROOT / "web" / "index.html"
TOPIC_MAP = ROOT / "web" / "problem-topics.json"
# Matched without their indentation, which the surrounding markup owns and has
# already changed once: wrapping the grid in a `<details>` moved it two columns
# right, and the six-space literals these used to be went on matching only
# because `str.find` searches for a substring. The block round-tripped, so
# `--check` stayed green while the anchors were wrong. Whatever indentation the
# page uses is read off the opening tag and written back, so nesting the section
# again is not a silent break.
START = '<section class="problem-grid" aria-label="Problems">'
END = "</section>"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def read_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def card(problem: dict[str, object], page: str, title: str) -> str:
    """One lobby card, named the way the interview will name the exercise.

    Keyed by page name, with the scenario title the recommendation line reads.
    A `coin-change` key, published title or "Dynamic Programming" tag tells the
    candidate what they are about to be asked, so none ships in the initial
    page. The published title and topic map are fetched only after the candidate
    opts into the corresponding picker control.
    """
    return "\n".join(
        [
            f'  <button class="problem-card" type="button" data-problem="{html.escape(page)}" data-difficulty="{html.escape(problem["difficulty"])}">',
            f'    <span class="problem-title">{html.escape(title)}</span>',
            '    <span class="problem-source" hidden></span>',
            f'    <span class="problem-meta">{html.escape(problem["difficulty"])}</span>',
            "  </button>",
        ]
    )


def generated(problems: list, pages: dict) -> str:
    cards = "\n".join(
        card(problem, pages[problem["id"]]["page"], pages[problem["id"]]["title"])
        for problem in problems
    )
    return "\n".join(
        [
            START,
            "  <!-- Generated by scripts/gen-problem-cards.py from problem-bank/. Do not edit by hand. -->",
            cards,
            END,
        ]
    )


def generated_topics(problems: list, pages: dict) -> str:
    """The opt-in topic filter's page-to-topic lookup."""
    mapping = {
        pages[problem["id"]]["page"]: problem.get("topics", [])
        for problem in problems
    }
    return json.dumps(mapping, ensure_ascii=False, indent=2) + "\n"


def main() -> int:
    args = parse_args()
    html_text = INDEX.read_text(encoding="utf-8")
    opening = re.search(
        rf"^([ \t]*){re.escape(START)}[ \t]*$", html_text, flags=re.MULTILINE
    )
    if opening is None:
        print(f"{INDEX}: could not find the problem-grid opening tag", file=sys.stderr)
        return 1

    indent = opening.group(1)
    # The close has to sit at the same indentation, so a nested `</section>`
    # cannot end the block early.
    end = re.compile(rf"^{indent}{re.escape(END)}[ \t]*$", flags=re.MULTILINE).search(
        html_text, opening.end()
    )
    if end is None:
        print(
            f"{INDEX}: the problem-grid section is not closed at its own indentation",
            file=sys.stderr,
        )
        return 1

    problems = read_json(SOURCE)
    pages = read_json(PAGE_MAP)
    block = textwrap.indent(generated(problems, pages), indent)
    updated = html_text[: opening.start()] + block + html_text[end.end() :]
    topics = generated_topics(problems, pages)
    current_topics = (
        TOPIC_MAP.read_text(encoding="utf-8") if TOPIC_MAP.exists() else ""
    )
    if args.check:
        stale = []
        if updated != html_text:
            stale.append("web/index.html problem cards")
        if topics != current_topics:
            stale.append("web/problem-topics.json")
        if stale:
            print(
                f"{', '.join(stale)} are stale; run: python3 scripts/gen-problem-cards.py",
                file=sys.stderr,
            )
            return 1
        return 0

    if updated != html_text:
        INDEX.write_text(updated, encoding="utf-8")
        print(f"updated {len(problems)} problem cards in web/index.html")
    if topics != current_topics:
        TOPIC_MAP.write_text(topics, encoding="utf-8")
        print(f"updated {len(problems)} problem topics in web/problem-topics.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
