#!/usr/bin/env python3
"""Regenerate lobby problem cards from problem-bank/problems.json."""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "problem-bank" / "problems.json"
INDEX = ROOT / "web" / "index.html"
DEFAULT_SELECTED = "two-sum"
START = '      <section class="problem-grid" aria-label="Problems">'
END = "      </section>"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def read_json(path: Path) -> object:
    return json.loads(path.read_text())


def card(problem: dict[str, object]) -> str:
    selected = " selected" if problem["id"] == DEFAULT_SELECTED else ""
    topics = ", ".join(html.escape(topic) for topic in problem["topics"])
    meta = f"{html.escape(problem['difficulty'])} &middot; {topics}"
    return "\n".join(
        [
            f'        <button class="problem-card{selected}" type="button" data-problem="{html.escape(problem["id"])}">',
            f'          <span class="problem-title">{html.escape(problem["title"])}</span>',
            f'          <span class="problem-meta">{meta}</span>',
            "        </button>",
        ]
    )


def generated() -> str:
    problems = read_json(SOURCE)
    cards = "\n".join(card(problem) for problem in problems)
    return "\n".join(
        [
            START,
            "        <!-- Generated by scripts/gen-problem-cards.py from problem-bank/problems.json. Do not edit by hand. -->",
            cards,
            END,
        ]
    )


def main() -> int:
    args = parse_args()
    html_text = INDEX.read_text()
    start = html_text.find(START)
    end = html_text.find(END, start)
    if start == -1 or end == -1:
        print(
            f"{INDEX}: could not find the problem-grid section markers", file=sys.stderr
        )
        return 1

    updated = html_text[:start] + generated() + html_text[end + len(END) :]
    if args.check:
        if updated != html_text:
            print(
                "web/index.html problem cards are stale; run: python3 scripts/gen-problem-cards.py",
                file=sys.stderr,
            )
            return 1
        return 0

    if updated != html_text:
        INDEX.write_text(updated)
        print(f"updated {len(read_json(SOURCE))} problem cards in web/index.html")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
