// Problem statements and browser judges, fetched one at a time.
//
// These used to be two modules, web/problems.js and web/judges.js, holding all
// 150 of each. Every candidate downloaded half a megabyte to work on one
// problem, and the judge module carried the expected output of every test case
// in the bank, so the answers to the other 149 arrived along with their own.
//
// Fetching one of each bounds that. It does not close it: the runner is in the
// browser, so a candidate can still read the judge for the problem they are
// working on. See `apply_test_results` in src/agent.rs for where that boundary
// is drawn and what it means for the report.
//
// Generated by scripts/gen-problems.py from problem-bank/.

/// Served when the URL names a problem the bank does not have, which is what
/// the old getProblem fallback did.
const DEFAULT_PROBLEM_ID = "two-sum";

/// Absent and unreachable are different answers, and the callers act on them
/// differently: a 404 means the bank does not have this one, anything else
/// means we could not find out. Bundling these into a single `null` is how a
/// dropped connection would get reported to a candidate as "this problem has
/// no test cases".
///
/// One retry, because the failure this guards against is a single dropped
/// request against the same origin that just served the page. A second failure
/// is a real outage and more attempts only delay saying so.
const ATTEMPTS = 2;

async function fetchJson(url) {
  let failure;
  // Bounded by the loop header rather than by guards inside it, so the number
  // of requests is readable without tracing the control flow.
  for (let attempt = 0; attempt < ATTEMPTS; attempt++) {
    try {
      const response = await fetch(url, { headers: { accept: "application/json" } });
      if (response.status === 404) return null;
      // Returned, not awaited: a malformed body is the caller's problem to see,
      // not something to retry as though the request had failed.
      if (response.ok) return response.json();
      failure = new Error(`${url} returned ${response.status}`);
    } catch (error) {
      failure = new Error(`${url} could not be reached: ${error.message}`);
    }
  }
  throw failure;
}

/// Resolves to a usable problem or rejects saying why. An unknown id is a bad
/// link rather than a broken interview, so it falls back to the default the way
/// the old bundled lookup did; a network failure is not a missing problem and
/// must not quietly become one.
export async function loadProblem(id) {
  const named = id ? await fetchJson(`/problems/${encodeURIComponent(id)}.json`) : null;
  return named ?? (await fetchJson(`/problems/${DEFAULT_PROBLEM_ID}.json`)) ?? Promise.reject(
    new Error(`the problem bank is missing its default problem, ${DEFAULT_PROBLEM_ID}`),
  );
}

/// Null when the bank has no judge for this problem, which the runner reports
/// as "no test cases are defined". Rejects when the judge exists but could not
/// be fetched, which is a different sentence for the candidate.
export async function loadJudge(id) {
  return id ? fetchJson(`/judges/${encodeURIComponent(id)}.json`) : null;
}
