// Problem statements and browser judges, fetched one at a time.
//
// These used to be two modules, web/problems.js and web/judges.js, holding all
// 150 of each. Every candidate downloaded half a megabyte to work on one
// problem, and the judge module carried the expected output of every test case
// in the bank, so the answers to the other 149 arrived along with their own.
//
// Fetching one of each bounds that. It does not close it: the runner is in the
// browser, so a candidate can still read the judge for the problem they are
// working on. See `apply_test_results` in src/agent.rs for where that boundary
// is drawn and what it means for the report.
//
// Generated by scripts/gen-problems.py from problem-bank/.

// Scenario names are what newly minted URLs carry, but interview links already
// in calendars and bookmarks carry published ids. The generated map preserves
// those links without restoring duplicate problem files, and is fetched only
// after the scenario-name lookup misses.
let pageMap;

const judges = new Map();

/// Absent and unreachable are different answers, and the callers act on them
/// differently: a 404 means the bank does not have this one, anything else
/// means we could not find out. Bundling these into a single `null` is how a
/// dropped connection would get reported to a candidate as "this problem has
/// no test cases".
///
/// One retry, because the failure this guards against is a single dropped
/// request against the same origin that just served the page. A second failure
/// is a real outage and more attempts only delay saying so.
const ATTEMPTS = 2;

async function fetchJson(url) {
  let failure;
  // Bounded by the loop header rather than by guards inside it, so the number
  // of requests is readable without tracing the control flow.
  for (let attempt = 0; attempt < ATTEMPTS; attempt++) {
    try {
      const response = await fetch(url, { headers: { accept: "application/json" } });
      if (response.status === 404) return null;
      // Returned, not awaited: a malformed body is the caller's problem to see,
      // not something to retry as though the request had failed.
      if (response.ok) return response.json();
      failure = new Error(`${url} returned ${response.status}`);
    } catch (error) {
      failure = new Error(`${url} could not be reached: ${error.message}`);
    }
  }
  throw failure;
}

/// Resolves to a usable problem or rejects saying why. An unknown id is a bad
/// link rather than a broken interview, so it falls back to the default the way
/// the old bundled lookup did; a network failure is not a missing problem and
/// must not quietly become one.
///
/// `page` is the scenario's page name from the URL; the problem it returns
/// carries the id everything else keys on.
export async function loadProblem(page) {
  const named = page ? await fetchJson(`/problems/${encodeURIComponent(page)}.json`) : null;
  if (named) return named;
  const pages = (await loadPageMap()) ?? {};
  if (page && Object.hasOwn(pages, page)) {
    const aliased = await fetchJson(`/problems/${encodeURIComponent(pages[page].page)}.json`);
    if (aliased) return aliased;
  }
  // The default is marked in the map, not named here: this module is served on
  // every load, and naming it here would carry a published id with it.
  const fallback = Object.values(pages).find((entry) => entry.default)?.page;
  const served = fallback && (await fetchJson(`/problems/${encodeURIComponent(fallback)}.json`));
  if (!served) throw new Error("the problem bank is missing its default problem");
  // Said, not silent: a link naming an exercise the bank does not have used to
  // open a different one as though that were what it asked for.
  return page ? { ...served, requestedPage: page } : served;
}

/// The published id of each problem, with its page, scenario title and
/// published title. Fetched only by the paths that start from a published id
/// or name: an old link, history saved before pages had names, and the lobby's
/// opt-in toggle. Cached for the page's lifetime once it arrives; a failed fetch
/// is forgotten, so a dropped connection costs one lookup rather than every
/// later one on the page.
export function loadPageMap() {
  pageMap ??= fetchJson("/problem-pages.json").catch((error) => {
    pageMap = undefined;
    throw error;
  });
  return pageMap;
}

/// `page` is the problem's page name, the only name the browser uses for it.
///
/// Null when the bank has no judge for this problem, which the runner reports
/// as "no test cases are defined". Rejects when the judge exists but could not
/// be fetched, which is a different sentence for the candidate.
///
/// Cached per id for the page's lifetime, the same way `loadPageMap` caches,
/// and for the same reason: the interview page, the candidate-case editor and
/// every test run ask for the one judge the candidate is working against. A
/// failed fetch is forgotten so a dropped connection costs one lookup rather
/// than every later one, and the rejection still reaches each caller.
export function loadJudge(id) {
  if (!id) return Promise.resolve(null);
  if (!judges.has(id)) {
    judges.set(id, fetchJson(`/judges/${encodeURIComponent(id)}.json`).catch((error) => {
      judges.delete(id);
      throw error;
    }));
  }
  return judges.get(id);
}
